aws_access_key = ""
aws_secret_key = ""
region = "us-east-1"
key_name = ""
key_file = "~/.ssh/id_rsa.pub"
s3_bucket_name = ""
availability_zones = "us-east-1b,us-east-1c,us-east-1d"
ecs_cluster_name = "sych-tf-cluster"